import type { Metadata } from "next";
import { AgentChat } from "@/components/AgentChat";

export const metadata: Metadata = {
  title: "AI Agent — Abanoub Malak",
  description:
    "Chat with Abanoub Malak's personal AI agent — it answers questions about his projects, skills, experience, and AI learning.",
};

export default function AgentPage() {
  return (
    <div className="mx-auto w-full max-w-5xl px-4 py-16 sm:px-6">
      <div className="mb-10">
        <p className="mb-2 text-sm font-semibold uppercase tracking-widest text-accent-strong dark:text-accent">
          Personal AI agent
        </p>
        <h1 className="text-4xl font-bold tracking-tight sm:text-5xl">
          Ask me anything
        </h1>
        <p className="mt-4 max-w-2xl text-base leading-relaxed text-zinc-600 dark:text-zinc-300">
          This is a real AI agent. It uses a large language model and calls
          structured tools (search, projects, skills, experience) backed by
          validated schemas — so it answers only from actual portfolio data,
          never invented facts.
        </p>
      </div>

      <AgentChat />

      <p className="mt-6 text-center text-xs text-zinc-400 dark:text-zinc-500">
        Responses are generated by an LLM and grounded in the structured
        portfolio data on this site.
      </p>
    </div>
  );
}